version: "3"
services:
    etl:
      build:
        context: ../../scripts
        dockerfile: ./Dockerfile
        args:
          LOGGER_ALERTING=${LOGGER_ALERTING}
          LOGGER_SLACK=${LOGGER_SLACK}
          SLACK_WEBHOOK=${SLACK_WEBHOOK}
          API_URL=${API_BASE_URL}
          POSTGRES_HOST=${POSTGRES_HOST}
          POSTGRES_DATABASE=${POSTGRES_DATABASE}
          POSTGRES_USERNAME=${POSTGRES_USERNAME}
          POSTGRES_PASSWORD=${POSTGREST_PASSWORD}
          RABBIT_MQ_HOST=${RABBIT_MQ_HOST}
          RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME}
          RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
          RABBIT_MQ_PATTERN=${RABBIT_MQ_PATTERN}
      container_name: midas-etl
      restart: unless-stopped
