version: "3"
services:
    frontend:
        build:
            context: ../../fe
            dockerfile: ./Dockerfile
            args:
                CHOKIDAR_USEPOLLING: "true"
                WATCHPACK_POLLING: "true"
                API_BASE_URL: ${API_BASE_URL}
                DB_SECRET: ${DB_SECRET}
        container_name: midas-frontend
        restart: unless-stopped
        environment:
            APP_ENV: "production"
            APP_DEBUG: "True"
            APP_PORT: 8080
        expose:
            - "8080"
        networks:
            - internal
    webserver:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: nginx
        container_name: midas-frontend-nginx
        restart: unless-stopped
        environment:
            APP_ENV: "production"
            APP_NAME: "webserver"
            APP_DEBUG: "false"
            SERVICE_NAME: "webserver"
        links:
            - frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginxdata:/var/log/nginx
        depends_on:
            - frontend
        networks:
            - internal
networks:
    internal:
        driver: bridge
volumes:
    appdata:
        driver: local
    nginxdata:
        driver: local
