deploy-local:
	cd deployments/local && docker-compose build
	cd deployments/local && docker-compose up -d

deploy-birdiescope:
	cd deployments/birdiescope && docker-compose build
	cd deployments/birdiescope && docker-compose up -d

deploy-magellan:
	cd deployments/magellan && docker-compose build
	cd deployments/magellan && docker-compose up -d